
services:
  postgres:
    image: postgres:17
    container_name: extrato-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: extrato-db
      POSTGRES_USER: extrato
      POSTGRES_PASSWORD: extrato
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.3
    container_name: extrato-keycloak
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/extrato-db
      KC_DB_USERNAME: extrato
      KC_DB_PASSWORD: extrato
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
