-- Criação da tabela para armazenar as instituições bancárias
CREATE TABLE instituicoes_bancarias
(
    id       SERIAL PRIMARY KEY,
    nome     VARCHAR(255) NOT NULL,
    cnpj     VARCHAR(20)  NOT NULL UNIQUE,
    classe   VARCHAR(100),
    segmento VARCHAR(100)
);

-- Inserção dos dados das instituições bancárias
INSERT INTO instituicoes_bancarias (nome, cnpj, classe, segmento)
VALUES ('BANCO DO BRASIL S.A.', '00.000.000', 'Banco Múltiplo', 'Banco do Brasil - Banco Múltiplo'),
       ('BRB - BANCO DE BRASILIA S.A.', '00.000.208', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('CAIXA ECONOMICA FEDERAL', '00.360.305', 'Caixa Econômica Federal', 'Caixa Econômica Federal'),
       ('BANCO INTER S.A.', '00.416.968', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO RIBEIRAO PRETO S.A.', '00.517.645', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BARI DE INVESTIMENTOS E FINANCIAMENTOS S.A.', '00.556.603', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO SEMEAR S.A.', '00.795.423', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO B3 S.A.', '00.997.185', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO RABOBANK INTERNATIONAL BRASIL S.A.', '1023570', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO COOPERATIVO SICREDI S.A.', '1181521', 'Banco Múltiplo Cooperativo', 'Banco Múltiplo Cooperativo'),
       ('BANCO BNP PARIBAS BRASIL S.A.', '1522368', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('KIRTON BANK S.A. - BANCO MÚLTIPLO', '1701201', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BRASILEIRO DE CRÉDITO SOCIEDADE ANÔNIMA', '1852137', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BV S.A.', '1858774', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO COOPERATIVO SICOOB S.A. - BANCO SICOOB', '2038232', 'Banco Múltiplo Cooperativo',
        'Banco Múltiplo Cooperativo'),
       ('BANCO KEB HANA DO BRASIL S.A.', '2318507', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO CATERPILLAR S.A.', '2658435', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO MORGAN STANLEY S.A.', '2801938', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('INTEX BANK BANCO DE CÂMBIO S.A.', '2992317', 'Banco de Câmbio', 'Banco de Câmbio'),
       ('BANCO CNH INDUSTRIAL CAPITAL S.A.', '2992446', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO J. SAFRA S.A.', '3017677', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO TOYOTA DO BRASIL S.A.', '3215790', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO ALFA S.A.', '3323840', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO ABN AMRO CLEARING S.A.', '3532415', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO CARGILL S.A.', '3609817', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO HONDA S.A.', '3634220', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BRADESCARD S.A.', '4184779', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('GOLDMAN SACHS DO BRASIL BANCO MULTIPLO S.A.', '4332281', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO AFINZ S.A. - BANCO MÚLTIPLO', '4814563', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO INBURSA S.A.', '4866275', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DA AMAZONIA S.A.', '4902979', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO DO ESTADO DO PARÁ S.A.', '4913711', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DE LAGE LANDEN BRASIL S.A.', '5040481', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BRADESCO BBI S.A.', '6271464', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BRADESCO FINANCIAMENTOS S.A.', '7207996', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DO NORDESTE DO BRASIL S.A.', '7237373', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO MONEO S.A.', '7441209', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANK OF CHINA (BRASIL) BANCO MÚLTIPLO S/A', '7450604', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO KDB DO BRASIL S.A.', '7656500', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO TOPÁZIO S.A.', '7679404', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO CSF S.A.', '8357240', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('MONEYCORP BANCO DE CÂMBIO S.A.', '8609934', 'Banco de Câmbio', 'Banco de Câmbio'),
       ('STATE STREET BRASIL S.A. - BANCO COMERCIAL', '9274232', 'Banco Comercial', 'Banco Comercial'),
       ('PICPAY BANK - BANCO MÚLTIPLO S.A', '9516419', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCOSEGURO S.A.', '10264663', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO YAMAHA MOTOR DO BRASIL S.A.', '10371492', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO AGIBANK S.A.', '10664513', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO DA CHINA BRASIL S.A.', '10690848', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BANDEPE S.A.', '10866788', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('SCANIA BANCO S.A.', '11417016', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO RANDON S.A.', '11476673', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO TRAVELEX S.A.', '11703662', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO FINAXIS S.A.', '11758741', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO SENFF S.A.', '11970623', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DO ESTADO DE SERGIPE S.A.', '13009717', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('EBURY BANCO DE CÂMBIO S.A.', '13059145', 'Banco de Câmbio', 'Banco de Câmbio'),
       ('BANCO WESTERN UNION DO BRASIL S.A.', '13720915', 'Banco Comercial', 'Banco Comercial'),
       ('PARANÁ BANCO S.A.', '14388334', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BOCOM BBM S.A.', '15114366', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BESA S.A.', '15124464', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('SOCIAL BANK BANCO MÚLTIPLO S/A', '15173776', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO WOORI BANK DO BRASIL S.A.', '15357060', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO NACIONAL S.A.', '17157777', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO MERCANTIL DO BRASIL S.A.', '17184037', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO ITAUCARD S.A.', '17192451', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO TRIANGULO S.A.', '17351180', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('ICBC DO BRASIL BANCO MÚLTIPLO S.A.', '17453575', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BRAZA BANK S.A. BANCO DE CÂMBIO', '19307785', 'Banco de Câmbio', 'Banco de Câmbio'),
       ('DEUTSCHE SPARKASSEN LEASING DO BRASIL BANCO MÚLTIPLO S.A.', '23511655', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO KOMATSU DO BRASIL S.A.', '23903068', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DIGIO S.A.', '27098060', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANESTES S.A. BANCO DO ESTADO DO ESPIRITO SANTO', '28127603', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO ABC BRASIL S.A.', '28195667', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO PACCAR S.A.', '28517628', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('STONEX BANCO DE CÂMBIO S.A.', '28811341', 'Banco de Câmbio', 'Banco de Câmbio'),
       ('SCOTIABANK BRASIL S.A. BANCO MÚLTIPLO', '29030467', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO HYUNDAI CAPITAL BRASIL S.A.', '30172491', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BTG PACTUAL S.A.', '30306294', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO MODAL S.A.', '30723886', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO CLASSICO S.A.', '31597552', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO C6 S.A.', '31872495', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO GUANABARA S.A.', '31880826', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO INDUSTRIAL DO BRASIL S.A.', '31895683', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO UBS (BRASIL) S.A.', '32062580', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DE LA NACION ARGENTINA', '33042151', 'Banco Comercial Estrangeiro - Filial no país',
        'Banco Comercial Estrangeiro - Filial no país'),
       ('CITIBANK N.A.', '33042953', 'Banco Comercial Estrangeiro - Filial no país',
        'Banco Comercial Estrangeiro - Filial no país'),
       ('BANCO CEDULA S.A.', '33132044', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BRADESCO BERJ S.A.', '33147315', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO J.P. MORGAN S.A.', '33172537', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO LOSANGO S.A. - BANCO MÚLTIPLO', '33254319', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO XP S.A.', '33264668', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO CAIXA GERAL - BRASIL S.A.', '33466988', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO CITIBANK S.A.', '33479023', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO RODOBENS S.A.', '33603457', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO FATOR S.A.', '33644196', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO MASTER MÚLTIPLO S.A.', '33884941', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO ITAÚ CONSIGNADO S.A.', '33885724', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO MASTER S/A', '33923798', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO IBM S.A.', '34270520', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO XCMG BRASIL S.A.', '36658769', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BNY MELLON BANCO S.A.', '42272526', 'Banco Comercial', 'Banco Comercial'),
       ('DAYCOVAL LEASING - BANCO MÚLTIPLO S.A.', '43818780', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DE LA PROVINCIA DE BUENOS AIRES', '44189447', 'Banco Comercial Estrangeiro - Filial no país',
        'Banco Comercial Estrangeiro - Filial no país'),
       ('BANCO GENIAL S.A.', '45246410', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('JPMORGAN CHASE BANK, NATIONAL ASSOCIATION', '46518205', 'Banco Comercial Estrangeiro - Filial no país',
        'Banco Comercial Estrangeiro - Filial no país'),
       ('BANCO ANDBANK (BRASIL) S.A.', '48795256', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BMG CONSIGNADO S.A.', '50585090', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO VOLKSWAGEN TRUCK & BUS S.A.', '52067630', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO HSBC S.A.', '53518684', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO ARBI S.A.', '54403563', 'Banco Comercial', 'Banco Comercial'),
       ('INTESA SANPAOLO BRASIL S.A. - BANCO MÚLTIPLO', '55230916', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO TRICURY S.A.', '57839805', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO VOLVO BRASIL S.A.', '58017179', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO SAFRA S.A.', '58160789', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BLUEBANK S.A.', '58497702', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO FIBRA S.A.', '58616418', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO VOLKSWAGEN S.A.', '59109165', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO LUSO BRASILEIRO S.A.', '59118133', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO GM S.A.', '59274605', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO PAN S.A.', '59285411', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO VOTORANTIM S.A.', '59588111', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO ITAUBANK S.A.', '60394079', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO MUFG BRASIL S.A.', '60498557', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO SUMITOMO MITSUI BRASILEIRO S.A.', '60518222', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('ITAÚ UNIBANCO S.A.', '60701190', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BRADESCO S.A.', '60746948', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO MERCEDES-BENZ DO BRASIL S.A.', '60814191', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('OMNI BANCO S.A.', '60850229', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('ITAÚ UNIBANCO HOLDING S.A.', '60872504', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO SOFISA S.A.', '60889128', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO VOITER S.A.', '61024352', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO CREFISA S.A.', '61033106', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO MIZUHO DO BRASIL S.A.', '61088183', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO INVESTCRED UNIBANCO S.A.', '61182408', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO BMG S.A.', '61186680', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO ITAÚ VEÍCULOS S.A.', '61190658', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO C6 CONSIGNADO S.A.', '61348538', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO SOCIETE GENERALE BRASIL S.A.', '61533584', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO PAULISTA S.A.', '61820817', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANK OF AMERICA MERRILL LYNCH BANCO MÚLTIPLO S.A.', '62073200', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO PINE S.A.', '62144175', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DAYCOVAL S.A.', '62232889', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO STELLANTIS S.A.', '62237425', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO RCI BRASIL S.A.', '62307848', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('DEUTSCHE BANK S.A. - BANCO ALEMAO', '62331228', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO BMG SOLUÇÕES FINANCEIRAS S.A.', '62421979', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO RENDIMENTO S.A.', '68900810', 'Banco Comercial', 'Banco Comercial'),
       ('BANCO BS2 S.A.', '71027866', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('NOVO BANCO CONTINENTAL S.A. - BANCO MÚLTIPLO', '74828799', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO CRÉDIT AGRICOLE BRASIL S.A.', '75647891', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO SISTEMA S.A.', '76543115', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO VR S.A.', '78626983', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('OURIBANK S.A. BANCO MÚLTIPLO', '78632767', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO RNX S.A.', '80271455', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO SANTANDER (BRASIL) S.A.', '90400888', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO JOHN DEERE S.A.', '91884981', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DO ESTADO DO RIO GRANDE DO SUL S.A.', '92702067', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO DIGIMAIS S.A.', '92874270', 'Banco Múltiplo', 'Banco Múltiplo'),
       ('BANCO ORIGINAL S.A.', '92894922', 'Banco Múltiplo', 'Banco Múltiplo');